# backend/k8s/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nest-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nest-backend
  template:
    metadata:
      labels:
        app: nest-backend
    spec:
      containers:
        - name: nest-backend
          image: jerrywang313/nest-server:v1
          volumeMounts:
            - name: config-volume
              mountPath: /app/config # Mount path for CONFIG_PATH
            - name: secret-volume
              mountPath: /app/secrets # Mount path for SECRETS_PATH
      volumes:
        - name: config-volume
          configMap:
            name: app-config # Reference the ConfigMap
        - name: secret-volume
          secret:
            secretName: app-secret
