apiVersion: apps/v1
kind: Deployment
metadata:
  name: nest-backend
  labels:
    app: nest-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nest-backend
  template:
    metadata:
      labels:
        app: nest-backend
    spec:
      containers:
        - name: nest-backend
          image: jerrywang313/nest-server:v1
          env:
            - name: CONFIG_PATH
              value: /app/config # Path to the config files
            - name: SECRETS_PATH
              value: /app/secrets # Path to the secret files
            # Use environment variables from ConfigMap
            - name: CORS_WHITELIST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: CORS_WHITELIST
            - name: HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: HOST
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: PORT
            # Use environment variables from Secret
            - name: SECRET_JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: SECRET_JWT_KEY
          volumeMounts:
            - name: config-volume
              mountPath: /app/config # Mount path for CONFIG_PATH (optional, if files are needed)
            - name: secret-volume
              mountPath: /app/secrets # Mount path for SECRETS_PATH (optional, if files are needed)
      volumes:
        - name: config-volume
          configMap:
            name: app-config # Reference the ConfigMap
        - name: secret-volume
          secret:
            secretName: app-secret # Reference the Secret
