# backend/k8s/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nest-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nest-backend
  template:
    metadata:
      labels:
        app: nest-backend
    spec:
      containers:
        - name: nest-backend
          image: jerrywang313/nest-server:v1
          env:
            - name: POSTGRES_HOST
              value: postgres-service
            - name: POSTGRES_USER
              value: user
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_DB
              value: mydb
          ports:
            - containerPort: 3000
